INSERT INTO PRODUCT (NAME, DESCRIPTION, TYPE, BRAND, COLOR, SIZE_NUMBER, SIZE, SELLER, QTY, PRICE, CREATED_DATE, UPDATED_DATE) VALUES
  ('Shirt Allen', 'Shirt from Allen', 'Shirt', 'ALLEN SOLLY', 'Green', 36, 'S', 'Amazon', 10, 500, now(), now());

INSERT INTO PRODUCT (NAME, DESCRIPTION, TYPE, BRAND, COLOR, SIZE_NUMBER, SIZE, SELLER, QTY, PRICE, CREATED_DATE, UPDATED_DATE) VALUES
  ('Shirt Allen', 'Shirt from Allen', 'Shirt', 'ALLEN SOLLY', 'Green', 40, 'M', 'Amazon', 10, 1000, now(), now());

INSERT INTO PRODUCT (NAME, DESCRIPTION, TYPE, BRAND, COLOR, SIZE_NUMBER, SIZE, SELLER, QTY, PRICE, CREATED_DATE, UPDATED_DATE) VALUES
  ('Shirt LEVIS', 'Shirt LEVIS', 'Shirt', 'LEVIS', 'Red', 40, 'L', 'Amazon', 10, 1000, now(), now());

INSERT INTO PRODUCT (NAME, DESCRIPTION, TYPE, BRAND, COLOR, SIZE_NUMBER, SIZE, SELLER, QTY, PRICE, CREATED_DATE, UPDATED_DATE) VALUES
  ('Shirt LEVIS', 'Shirt LEVIS', 'Shirt', 'LEVIS', 'Red', 39, 'M', 'Amazon', 10, 1000, now(), now());

INSERT INTO PRODUCT (NAME, DESCRIPTION, TYPE, BRAND, COLOR, SIZE_NUMBER, SIZE, SELLER, QTY, PRICE, CREATED_DATE, UPDATED_DATE) VALUES
  ('Shirt from Levis', 'Shirt from Levis', 'Jeans', 'LEVIS', 'Yellow', 40, 'M', 'Amazon', 10, 1000, now(), now());

INSERT INTO PRODUCT (NAME, DESCRIPTION, TYPE, BRAND, COLOR, SIZE_NUMBER, SIZE, SELLER, QTY, PRICE, CREATED_DATE, UPDATED_DATE) VALUES
  ('Shirt from Levis', 'Shirt from Levis', 'Caps', 'LEVIS', 'Red', 40, 'M', 'Amazon', 10, 1000, now(), now());

INSERT INTO PRODUCT (NAME, DESCRIPTION, TYPE, BRAND, COLOR, SIZE_NUMBER, SIZE, SELLER, QTY, PRICE, CREATED_DATE, UPDATED_DATE) VALUES
  ('TShirt from Lee Cooper', 'TShirt from Lee Cooper', 'Tshirt', 'LEE COOPER', 'Black', 40, 'S', 'Amazon', 10, 1000, now(), now());

INSERT INTO PRODUCT (NAME, DESCRIPTION, TYPE, BRAND, COLOR, SIZE_NUMBER, SIZE, SELLER, QTY, PRICE, CREATED_DATE, UPDATED_DATE) VALUES
  ('TShirt from Lee Cooper', 'TShirt from Lee Cooper', 'Tshirt', 'LEE COOPER', 'Blue', 40, 'M', 'Amazon', 10, 1000, now(), now());
